import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.swifttranslator.com/');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mama gedhara yanavaa ban hithuvata vadaa godak raee velaa.');
  await page.getByText('මම ගෙදර යනවා බන් හිතුවට වඩා ගොඩක් රෑ වෙලා').click();
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('ammoo saeehena kaalekinne hambunee komadha ithin');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill(' hari, mama karannam ammaa.');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('hiruni dhaekkadha apee tiktok video eka eka supiri nedha ?');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('man coding lessons tika baeluvaa tika tika ....... thava thiyanava ithin\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('api next week eke ayiyage manamaali balanna yanavaa\n');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('api next week ekee ayiyage manamaali balanna yanavaa\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('heta apee malli AL exam ekata yanavaa.\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('oyaa adha office giya naedhdha kiyala mata ahanna hithuna mokadha uba godak busy vidhihatane hitiyee.\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('oyaa saamaanya vidhihata kaalayak gaththoth oyaata hithenne naethi dheevaluth hithala balanna puluvan mokadha jiivithayata adhaala hodha thiiranaya ganna kalaya hari vaedhagath \n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('man pansal yano\n');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('man pansal yanoo\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('kaanthi akkaa heta ennadha aehuva dharuva ekka ara sahanaadhaara dhenava kiyapu eka ganna \n');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('kaanthi akkaa heta ennadha aehuvaa dharuva ekka ara sahanaadhaara dhenava kiyapu eka ganna \n');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('kaanthi akkaa heta ennadha aehuvaa dharuvaa ekka ara sahanaadhaara dhenava kiyapu eka ganna \n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('handhiye traffic light eka gaava edhaa uu idhiya dhaekke\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('podi ayya ekka kolaba yanava badu vagayak ganna kiiyata enna puluvan veidha dhan naee oyaa mokadha kiyanne hetama enavadha ???\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('adoo vaedak karanna gaththanam eeka hariyata karapanko bQQ. \n');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('adoo vaedak karanna gaththanam eeka hariyata karapanko bQQ.\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('heta ape miss eyidha sure ekatama?\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('sapuni, heta chaamara gedhara yanava kivva. oyaata heta BOC ATM eka gaavata enna puluvanda ahuva 10.45am vage.\n');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowUp');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('sapuni, heta chaamara gedhara yanava kivva. oyaata heta BOC ATM eka gaavata enna puluvandha ahuva 10.45am vage.\n');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('sapuni, heta chaamara gedhara yanava kivva. oyaata heta BOC ATM eka gaavata enna puluvandha aehuva 10.45am vage.\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('class ekata log vena URL eka incorrect kiyla vaetenvane haemavelema aeyi e?\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mata sandwich  ekak oni\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('oyaa kohee idhandha aavee?\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('mata heta udhee 10ta vagee maharagamata yanna thiyanavaa ban , ee hindhaa mama adha komahari komahari mee paper eka ivara karaganna balanna oonii naethnam heta physics class ekata gihin baaradhenna vidhiyak naehaene.... \n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('amith: machan sureesh, adha kohedha yannee? sureeSh: adha nam vaeda tikak thiyenavaa ban. uBAta kohedha yanna thiyennee? amith: mee mama hithuvee tavun ekata gihin poddak kanna kiyalaa. uBAth enavadha? sureeSh: hoDHA adhahasak nee. vaeda tika ivara karalaa maath ennam kolloo. amith: ehenam havasa 5ta bus stand eka Laga set vemuu. sureeSh: okay ban. adha kaalekata passee aathal ekak ganna puluvan veyi. amith: aeththatama. yaaluvoo ekka innakotama thamayi maara nidhahasak dhaenennee. sureesh: hari hari, ehenam havasata setvemuu aruutath kiyannam mama dhineeshta\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('karunaakaralaa meheta enavaa !\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Click on a link that is broken\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Enter numbers or symbols in a text field expecting text\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Leave mandatory field blank and submit\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Click “Get started” button before page fully loads\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Open homepage\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Open a page that loads slowly\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Enter random string in search (e.g., “xyz123abc”)\n');
  await page.getByLabel('Clear').click();
  await page.locator('.flex.items-center.gap-2.mt-2').first().click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Click Docs menu link\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Resize browser to small screen\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Go to https://playwright.dev/wrongpage\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Enter numbers/symbols in text-only field\n');
  await page.getByLabel('Clear').click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('Resize browser to small screen\n');
  await page.getByLabel('Clear').click();
});